### PR TITLE
Fix readme typo: disabling auto git maintenance

### PR DESCRIPTION
**Pull request by Gee19**
Couldn't get this working based on the example in the readme, this seemed to fix it. :jack_o_lantern:

### CODE REVIEW

**Comment by marlonrichert** [comment]
It works for me. Can you please share what you actually tried to use in practice?

**Comment by Gee19** [comment]
Yep np, tried both the following but neither disabled git maintenance:

```
zstyle 'znap:*:*' git-maintenance off
zstyle 'znap:*' git-maintenance off
```

**Comment by marlonrichert** [comment]
Ah, now I see typo. I really couldn't see it before. 😅  Thanks!

**Comment by marlonrichert** [comment]
Merged in 4d192db.

**Pull request closed without merging**
